version: "3.3"
services: 
  jupyter:
    image: akolotov/anaconda3-web3
    ports: 
     - "8888:8888"
    entrypoint: 
     - /opt/conda/bin/jupyter 
     - notebook 
     - --notebook-dir=/opt/notebooks
     - --ip='0.0.0.0'
     - --port=8888 
     - --no-browser 
     - --allow-root
